name: Release
on:
  push:
    branches:
      - main
    paths:
      - "VERSION"

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Version ENV
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
    outputs:
      version: v${{ env.VERSION }}

  docker-build-push:
    needs:
      - generate-version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ghcr.io/fkmeland/${{ github.event.repository.name }}:${{ needs.generate-version.outputs.version }}

  create-release:
    needs:
      - generate-version
      - docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.generate-version.outputs.version }}
          release_name: ${{ needs.generate-version.outputs.version }}
